### ISSUE TITLE
Asahi-bless on mac throws error

### ISSUE THREAD

**Issue by darinkishore** [WhatAmISupposedToPutHere/asahi-nvram#13]
### Issue Description
When attempting to use `asahi-bless` to change the active boot partition on an M1 Pro MBPro, an error occurs. This issue was encountered after successfully using `asahi-bless` in Asahi Linux and then switching back to macOS.

### Environment
- **Operating System:** macOS Sonoma 14.2.1
- **Shell:** Fish (issue persists in Zsh when launched from Fish shell)
- **asahi-bless Version:** 0.3.0

### Steps to Reproduce
1. Run `asahi-bless` on macOS with the following command: `sudo env RUST_BACKTRACE=full asahi-bless`.
2. Note that the error does not occur in Asahi Linux when run with `sudo`.

### Expected Behavior
The tool should execute without errors and allow for changing the active boot partition.

### Actual Behavior
The following panic is encountered:

```plaintext
❯ sudo env RUST_BACKTRACE=full asahi-bless
thread 'main' panicked at /Users/darin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/asahi-bless-0.3.0/src/lib.rs:265:10:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:        0x100727400 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb1669d376cd16fb9
   1:        0x100735350 - core::fmt::write::hfb70cbdb2260ac51
   2:        0x10071f004 - std::io::Write::write_fmt::h70ee144642a582c5
   3:        0x10072723c - std::sys_common::backtrace::print::h404168d6289bebbe
   4:        0x100716d7c - std::panicking::default_hook::{{closure}}::hcad9841f2663dad9
   5:        0x100716ad4 - std::panicking::default_hook::he7ca7c46dc216a28
   6:        0x100717240 - std::panicking::rust_panic_with_hook::h501076dcf33dacb0
   7:        0x1007277ec - std::panicking::begin_panic_handler::{{closure}}::h0665b0808da4d87c
   8:        0x100727608 - std::sys_common::backtrace::__rust_end_short_backtrace::h6d7b13146df55e47
   9:        0x100716fd8 - _rust_begin_unwind
  10:        0x10073f884 - core::panicking::panic_fmt::h5de4b603c189570c
  11:        0x10073fb9c - core::result::unwrap_failed::h6c2edae44e6d47ca
  12:        0x1006e741c - asahi_bless::get_boot_candidates::he3eb3062ee89c7ca
  13:        0x10069b988 - asahi_bless::list_boot_volumes::h374a76da61279196
  14:        0x10069b2e0 - asahi_bless::main::h5d7225de80af166f
  15:        0x1006a0a98 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8cefa744bb8b74bf
  16:        0x10069fab0 - std::rt::lang_start::{{closure}}::h5ef6d4c13ee96b3b
  17:        0x100716ec8 - std::panicking::try::h8fbeda15452e3045
  18:        0x10070fc3c - std::rt::lang_start_internal::h74e1b60c5b4153f8
  19:        0x10069d21c - _main
  ```

### Additional Context
- This error mirrors one previously encountered on Asahi Linux when not using `sudo`, but on macOS, the issue persists even with elevated permissions.
- The error suggests an issue with file path resolution or access permissions.

### Request
Could you please investigate the cause of this error and provide a fix or workaround? Any insights or updates would be greatly appreciated. Thank you so much!

**Comment by nohajc** [comment]
FYI, macOS has its own built-in command line tool `bless` for this purpose. It's pretty low-level though, so it's probably safer to use the Startup Disk settings UI.
