### ISSUE TITLE
When used interactively, add a more descriptive prompt and show a message if the operation succeeded

### ISSUE THREAD

**Issue by rxhfcy** [WhatAmISupposedToPutHere/asahi-nvram#19]
New users, especially non-experts, won't automatically know what `asahi-bless` is, or how it is used.
It would be really nice (and user-friendly!) if asahi-bless held the user's hand a little bit more when used interactively (also see #5)

**"Before" (no feedback)**
```
$ sudo asahi-bless 
 1) Macintosh HD
*2) Fedora Linux
==> 1
$ echo I have no idea what I just tried to do, and/or if it worked
```

**Suggestions:**

1) instead of just displaying "==>", add an explanation of what `asahi-bless` is asking the user to choose
2) after pressing enter, inform the user if the operation was successful

**"After": (add "Select default startup disk:" + show a message after successfully setting the new default startup disk)** 
```
$ sudo asahi-bless 
 1) Macintosh HD
*2) Fedora Linux

Select default startup disk:
==> 1

"Macintosh HD" will be used by default when starting up your computer.
$ echo 👍
```

Alternative wording suggestions for the prompt:
- "Select the system you want to use to start up your computer:" (note: this is the wording macOS uses here:  Menu / System Settings... / General / Startup Disk)
- "Select the disk you want to use to start up your computer:" (inspired by the above)
- "Select the disk you want to use by default when starting up your computer:" (slight variation)
- "Which disk do you want to use by default when starting up the computer:"
- "Select default startup disk:" (probably my favorite)
==>

Alternative wording suggestions for the "success message":
- ""Macintosh HD" successfully set as the default startup disk."
- (e.g. "Volume Macintosh HD successfully set as the default boot target" would be needlessly technical and non-descriptive here IMHO)
- ""Macintosh HD" will be used by default when starting up your computer." (probably my favorite)
- "From now on, "Macintosh HD" will be used to start up your computer." (I like this one too)

I'm not a UX expert but I've watched several non-experts use computers. In general, I really think that `asahi-bless` should use as "non-jargony" and "user-friendly" language as possible (i.e. "disk" instead of "volume", "startup disk" instead of "boot target", etc), and generally just use terminology similar to what Apple already uses in their "customer-facing" UI, because that's the language normal people might actually have a chance of understanding (without being any more confusing for the more technical users).

**Comment by WhatAmISupposedToPutHere** [comment]
Fixed in #26
