### ISSUE TITLE
New release for the asahi-bless crate?

### ISSUE THREAD

**Issue by rxhfcy** [WhatAmISupposedToPutHere/asahi-nvram#27]
@WhatAmISupposedToPutHere Could you please make another new release for `asahi-bless`? There have been some pretty useful fixes since the last release (especially the user-friendly UI tweaks and the --version flag).

I'm just a normal user, but it would be great if there was an updated `asahi-bless` version as soon as possible. Thanks for considering this!

**Comment by nohajc** [comment]
@WhatAmISupposedToPutHere Bump.
