### ISSUE TITLE
How to use this? More readme?

### ISSUE THREAD

**Issue by hamza72x** [WhatAmISupposedToPutHere/asahi-nvram#5]
Hey! How to use this? I want to set macOS as boot drive from Linux directly.

_**Being a noob in this area, sorry about that.**_

**Comment by WhatAmISupposedToPutHere** [comment]
Run asahi-bless. It will print out a numbered list of all apfs volume groups that it considers bootable. Enter the number next to the os that you want to set as default boot and press enter.
